[package]
name = "tt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[package.metadata.winrt.dependencies]
"Microsoft.WinUI" = "3.0.0-preview4.210210.4"